### PR TITLE
更还原的人机验证

### PR DESCRIPTION
**Pull request by jianjianai**
image

### CODE REVIEW

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/50731824315309e3d212c5203947af66852d3b0c/api/challenge.go#L10-L86

这里也需要修改一下

**Comment by jianjianai** [comment]
ok

**Review by Harry-zklcdc — COMMENTED** [review]
Merge pull request #442 from jianjianai/master

**Comment by Harry-zklcdc** [comment]
已合并

**Pull request closed without merging**
