### PR TITLE
[Fix] 🐛 "clearCache" take effect on KievRPSSecAuth

### PR DESCRIPTION
**Pull request by IT-HaoGe**
修复"一键重置"未清除 KievRPSSecAuth 值的问题

### CODE REVIEW

**Comment by IT-HaoGe** [comment]
Close #48

**Review by Harry-zklcdc — APPROVED** [review]
[Fix] 🐛 "clearCache" take effect on KievRPSSecAuth

**Comment by Harry-zklcdc** [comment]
已合并
Commit: 12a76eb4edf1ebb3d50c3bf19e6502794cd1064d

**Comment by Harry-zklcdc** [comment]
已构建二进制文件
Release: https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.10.1

**Pull request closed without merging**
